"""empty message

Revision ID: 5440dc37ea47
Revises: 19048e08bebb
Create Date: 2014-09-30 23:37:13.500781

"""

# revision identifiers, used by Alembic.
revision = '5440dc37ea47'
down_revision = '19048e08bebb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', u'avatar_hash')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(u'avatar_hash', sa.VARCHAR(length=32), nullable=True))
    ### end Alembic commands ###
